Vagrant.configure("2") do |config|
  # General configuration for all VMs
  gui = false
  ram = 2048
  cpus = 2

  # All VMs will use the same box
  config.vm.box = "almalinux/9"

  config.vm.define "aaammariS" do |server|
    server.vm.hostname="aaammariS"
    server.vm.provider "virtualbox" do |vb|
      vb.name="aaammariS"
      vb.memory=ram
      vb.cpus=cpus
      vb.gui = gui
    end 
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision :shell, path: "scripts/provision-server.sh"
  end
  
  config.vm.define "aaammariSW" do |worker|
    worker.vm.hostname="aaammariSW"
    worker.vm.provider "virtualbox" do |vb|
      vb.name="aaammariSW"
      vb.memory=ram
      vb.cpus=cpus
      vb.gui = gui
    end
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision :shell, path:  "scripts/provision-worker.sh"
  end

end